apiVersion: v1
kind: ConfigMap
metadata:
  name: recommend-config
  namespace: dg0411-lifesub-ns
data:
  SERVER_PORT: "8083"
  POSTGRES_HOST: "postgres-recommend-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "recommend"
