apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: dg0411-lifesub-ns
  labels:
    app: member
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: member
