apiVersion: v1
kind: Service
metadata:
  name: mysub-service
  namespace: dg0411-lifesub-ns
  labels:
    app: mysub
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: mysub
