# .github/workflows/cicd.yaml
name: Backend CI/CD Pipeline

on:
  push:
    branches: 
      - main

env:
  REGISTRY: acrdigitalgarage02.azurecr.io

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build applications
        run: |
          ./gradlew :member:build :mysub-infra:build :recommend:build -x test

      - name: Run tests and generate coverage reports
        run: |
          ./gradlew :member:test :member:jacocoTestReport
          ./gradlew :mysub-infra:test :mysub-infra:jacocoTestReport
          ./gradlew :recommend:test :recommend:jacocoTestReport

      - name: SonarQube Analysis - Member Service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -n "${{ secrets.SONAR_HOST_URL }}" ] && [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
            ./gradlew :member:sonar \
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
              -Dsonar.projectKey=lifesub-member-dg0411 \
              -Dsonar.projectName=lifesub-member-dg0411 \
              -Dsonar.java.binaries=build/classes/java/main \
              -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
              -Dsonar.exclusions=**/config/**,**/entity/**,**/dto/**,**/*Application.class,**/exception/**
          else
            echo "SonarQube secrets not configured - skipping analysis"
          fi

      - name: SonarQube Analysis - MySub Service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -n "${{ secrets.SONAR_HOST_URL }}" ] && [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
            ./gradlew :mysub-infra:sonar \
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
              -Dsonar.projectKey=lifesub-mysub-dg0411 \
              -Dsonar.projectName=lifesub-mysub-dg0411 \
              -Dsonar.java.binaries=build/classes/java/main \
              -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
              -Dsonar.exclusions=**/config/**,**/entity/**,**/dto/**,**/*Application.class,**/exception/**
          else
            echo "SonarQube secrets not configured - skipping analysis"
          fi

      - name: SonarQube Analysis - Recommend Service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -n "${{ secrets.SONAR_HOST_URL }}" ] && [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
            ./gradlew :recommend:sonar \
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
              -Dsonar.projectKey=lifesub-recommend-dg0411 \
              -Dsonar.projectName=lifesub-recommend-dg0411 \
              -Dsonar.java.binaries=build/classes/java/main \
              -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
              -Dsonar.exclusions=**/config/**,**/entity/**,**/dto/**,**/*Application.class,**/exception/**
          else
            echo "SonarQube secrets not configured - skipping analysis"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            member/build/libs/*.jar
            mysub-infra/build/libs/*.jar
            recommend/build/libs/*.jar

  release:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read deployment environment variables
        run: |
          # deployment/deploy_env_vars 파일에서 환경변수 읽기
          while IFS='=' read -r key value; do
            # 주석과 빈 줄 제외
            if [[ ! "$key" =~ ^#.* ]] && [[ -n "$key" ]]; then
              # 환경변수로 설정
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < deployment/deploy_env_vars

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Set image tag
        id: set-tag
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push member service image
        run: |
          docker build \
            --build-arg BUILD_LIB_DIR="member/build/libs" \
            --build-arg ARTIFACTORY_FILE="member.jar" \
            -f deployment/container/Dockerfile \
            -t ${{ env.registry }}/${{ env.image_org }}/member:${{ env.IMAGE_TAG }} .
          docker push ${{ env.registry }}/${{ env.image_org }}/member:${{ env.IMAGE_TAG }}

      - name: Build and push mysub service image
        run: |
          docker build \
            --build-arg BUILD_LIB_DIR="mysub-infra/build/libs" \
            --build-arg ARTIFACTORY_FILE="mysub.jar" \
            -f deployment/container/Dockerfile \
            -t ${{ env.registry }}/${{ env.image_org }}/mysub:${{ env.IMAGE_TAG }} .
          docker push ${{ env.registry }}/${{ env.image_org }}/mysub:${{ env.IMAGE_TAG }}

      - name: Build and push recommend service image
        run: |
          docker build \
            --build-arg BUILD_LIB_DIR="recommend/build/libs" \
            --build-arg ARTIFACTORY_FILE="recommend.jar" \
            -f deployment/container/Dockerfile \
            -t ${{ env.registry }}/${{ env.image_org }}/recommend:${{ env.IMAGE_TAG }} .
          docker push ${{ env.registry }}/${{ env.image_org }}/recommend:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read deployment environment variables
        run: |
          # deployment/deploy_env_vars 파일에서 환경변수 읽기
          while IFS='=' read -r key value; do
            # 주석과 빈 줄 제외
            if [[ ! "$key" =~ ^#.* ]] && [[ -n "$key" ]]; then
              # 환경변수로 설정
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < deployment/deploy_env_vars

      - name: Set image tag from previous job
        run: |
          echo "IMAGE_TAG=${{ needs.release.outputs.image-tag }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group rg-digitalgarage-02 --name aks-digitalgarage-02 --overwrite-existing

      - name: Create namespace
        run: |
          kubectl create namespace ${{ env.namespace }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Generate Kubernetes manifest
        run: |
          # 환경변수 설정
          export namespace=${{ env.namespace }}
          export allowed_origins=${{ env.allowed_origins }}
          export ingress_host=${{ env.ingress_host }}
          export jwt_secret_key=${{ env.jwt_secret_key }}
          export postgres_user=${{ env.postgres_user }}
          export postgres_password=${{ env.postgres_password }}
          export replicas=${{ env.replicas }}
          export resources_requests_cpu=${{ env.resources_requests_cpu }}
          export resources_requests_memory=${{ env.resources_requests_memory }}
          export resources_limits_cpu=${{ env.resources_limits_cpu }}
          export resources_limits_memory=${{ env.resources_limits_memory }}
          
          # 이미지 경로 환경변수 설정
          export member_image_path=${{ env.registry }}/${{ env.image_org }}/member:${{ env.IMAGE_TAG }}
          export mysub_image_path=${{ env.registry }}/${{ env.image_org }}/mysub:${{ env.IMAGE_TAG }}
          export recommend_image_path=${{ env.registry }}/${{ env.image_org }}/recommend:${{ env.IMAGE_TAG }}
          
          # manifest 생성
          envsubst < deployment/deploy.yaml.template > deployment/deploy.yaml

      - name: Debug - Show generated manifest
        run: |
          echo "Generated manifest content:"
          cat deployment/deploy.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/deploy.yaml

      - name: Wait for deployments to be ready
        run: |
          echo "Waiting for deployments to be ready..."
          kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/member --timeout=300s
          kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/mysub --timeout=300s
          kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/recommend --timeout=300s

      - name: Display deployment status
        run: |
          echo "========================================="
          echo "Backend services deployment completed!"
          echo "Member Service: Ready"
          echo "MySub Service: Ready"
          echo "Recommend Service: Ready"
          echo "Ingress Host: ${{ env.ingress_host }}"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"
          echo "========================================="