# .github/workflows/cicd.yaml
name: Backend CI/CD Pipeline

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  REGISTRY: acrdigitalgarage02.azurecr.io

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build applications
        run: |
          echo "Building member service..."
          ./gradlew :member:clean :member:build
          echo "Building mysub service..."
          ./gradlew :mysub-infra:clean :mysub-infra:build
          echo "Building recommend service..."
          ./gradlew :recommend:clean :recommend:build

      - name: Run tests
        run: |
          echo "Testing member service..."
          ./gradlew :member:test
          echo "Testing mysub service..."
          ./gradlew :mysub-infra:test
          echo "Testing recommend service..."
          ./gradlew :recommend:test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            member/build/libs/*.jar
            mysub-infra/build/libs/*.jar
            recommend/build/libs/*.jar
          retention-days: 1

  release:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read deployment environment variables
        run: |
          while IFS= read -r line || [ -n "$line" ]; do
            if [[ ! "$line" =~ ^# ]] && [[ "$line" =~ = ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < deployment/deploy_env_vars

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Set image tag
        id: set-tag
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Generated image tag: $IMAGE_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push member service image
        run: |
          echo "Building member service image..."
          docker build \
            --build-arg BUILD_LIB_DIR="member/build/libs" \
            --build-arg ARTIFACTORY_FILE="member.jar" \
            -f deployment/container/Dockerfile \
            -t ${{ env.registry }}/${{ env.image_org }}/member:${{ env.IMAGE_TAG }} .
          docker push ${{ env.registry }}/${{ env.image_org }}/member:${{ env.IMAGE_TAG }}
          echo "Successfully pushed member:${{ env.IMAGE_TAG }}"

      - name: Build and push mysub service image
        run: |
          echo "Building mysub service image..."
          docker build \
            --build-arg BUILD_LIB_DIR="mysub-infra/build/libs" \
            --build-arg ARTIFACTORY_FILE="mysub.jar" \
            -f deployment/container/Dockerfile \
            -t ${{ env.registry }}/${{ env.image_org }}/mysub:${{ env.IMAGE_TAG }} .
          docker push ${{ env.registry }}/${{ env.image_org }}/mysub:${{ env.IMAGE_TAG }}
          echo "Successfully pushed mysub:${{ env.IMAGE_TAG }}"

      - name: Build and push recommend service image
        run: |
          echo "Building recommend service image..."
          docker build \
            --build-arg BUILD_LIB_DIR="recommend/build/libs" \
            --build-arg ARTIFACTORY_FILE="recommend.jar" \
            -f deployment/container/Dockerfile \
            -t ${{ env.registry }}/${{ env.image_org }}/recommend:${{ env.IMAGE_TAG }} .
          docker push ${{ env.registry }}/${{ env.image_org }}/recommend:${{ env.IMAGE_TAG }}
          echo "Successfully pushed recommend:${{ env.IMAGE_TAG }}"

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read deployment environment variables
        run: |
          while IFS= read -r line || [ -n "$line" ]; do
            if [[ ! "$line" =~ ^# ]] && [[ "$line" =~ = ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < deployment/deploy_env_vars

      - name: Set image tag from previous job
        run: |
          echo "IMAGE_TAG=${{ needs.release.outputs.image-tag }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group rg-digitalgarage-02 --name aks-digitalgarage-02 --overwrite-existing

      - name: Create namespace if not exists
        run: |
          kubectl create namespace ${{ env.namespace }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Generate Kubernetes manifest
        run: |
          export namespace=${{ env.namespace }}
          export allowed_origins=${{ env.allowed_origins }}
          export ingress_host=${{ env.ingress_host }}
          export jwt_secret_key=${{ env.jwt_secret_key }}
          export postgres_user=${{ env.postgres_user }}
          export postgres_password=${{ env.postgres_password }}
          export replicas=${{ env.replicas }}
          export resources_requests_cpu=${{ env.resources_requests_cpu }}
          export resources_requests_memory=${{ env.resources_requests_memory }}
          export resources_limits_cpu=${{ env.resources_limits_cpu }}
          export resources_limits_memory=${{ env.resources_limits_memory }}
          export member_image_path=${{ env.registry }}/${{ env.image_org }}/member:${{ env.IMAGE_TAG }}
          export mysub_image_path=${{ env.registry }}/${{ env.image_org }}/mysub:${{ env.IMAGE_TAG }}
          export recommend_image_path=${{ env.registry }}/${{ env.image_org }}/recommend:${{ env.IMAGE_TAG }}
          
          envsubst < deployment/deploy.yaml.template > deployment/deploy.yaml

      - name: Debug - Show generated manifest
        run: |
          echo "Generated manifest content:"
          cat deployment/deploy.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/deploy.yaml

      - name: Wait for deployments to be ready
        run: |
          echo "Waiting for deployments to be ready..."
          kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/member --timeout=300s
          kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/mysub --timeout=300s
          kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/recommend --timeout=300s

      - name: Verify deployment
        run: |
          echo "Checking pod status..."
          kubectl -n ${{ env.namespace }} get pods
          
          echo "Checking service status..."
          kubectl -n ${{ env.namespace }} get svc
          
          echo "Checking ingress status..."
          kubectl -n ${{ env.namespace }} get ingress

      - name: Display deployment status
        run: |
          echo "========================================="
          echo "Backend services deployment completed!"
          echo "Member Service: Ready"
          echo "MySub Service: Ready"
          echo "Recommend Service: Ready"
          echo "Ingress Host: ${{ env.ingress_host }}"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"
          echo "========================================="